name: Auto assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  auto-assign:
    uses: devops-ia/.github/.github/workflows/auto-assign.yaml@main
    with:
      teams: devops-ia
    secrets: inherit
